python main_test.py \
--image_dir /jhcnas1/chenzhixuan/mimic-cxr-jpg/images_resized/ \
--ann_path /jhcnas1/chenzhixuan/mimic-cxr-jpg/annotation.json \
--dataset_name mimic_cxr \
--max_seq_length 100 \
--threshold 10 \
--batch_size 16 \
--epochs 30 \
--save_dir results/mimic_cxr \
--step_size 1 \
--gamma 0.8 \
--seed 42 \
--load /home/chenzhixuan/Workspace/R2Gen/results/mimic_cxr/model_best.pth \
--beam_size 2
